language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules

before_script:
  - yarn start --silent &

script:
  # run unit tests:
  - yarn test
  # run E2E tests:
  - $(npm bin)/cypress run --record
